AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Metadata:
  AWS::ServerlessRepo::Application:
    Name: codepipeline-multi-manual-approvals
    Description: 'Serverless application that enable multiple manual approvals on AWS CodePipeline.'
    Author: phucnh
    SpdxLicenseId: MIT
    LicenseUrl: s3://codepipeline-multi-manual-approvals/metadata/LICENSE
    ReadmeUrl: s3://codepipeline-multi-manual-approvals/metadata/README.md
    Labels: ['codepipeline', 'approval-process', 'multiple-manual-approvals']
    HomePageUrl: https://github.com/CyberAgent/codepipeline-multi-manual-approvals.git
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/CyberAgent/codepipeline-multi-manual-approvals.git
Description: 'Allow multiple manual approvals on AWS CloudPipeline'
Resources:
  approvalChecker:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/approval-checker.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Description:
      MemorySize: 128
      Timeout: 10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - codepipeline:GetPipelineState
                - codepipeline:GetPipeline
              Resource:
                - !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:*
            - Effect: Allow
              Action:
                - codepipeline:PutJobFailureResult
                - codepipeline:PutJobSuccessResult
              Resource: '*'
Outputs:
  approvalCheckerFnName:
    Description: 'The name of approval check function'
    Value: !Ref approvalChecker
    Export:
      Name: !Sub ${AWS::StackName}-approvalChecker
